### ISSUE TITLE
Multifaders - MIDI error

### ISSUE THREAD

**Issue by brunetton** [jean-emmanuel/open-stage-control#247]
Hi, 

I'm using OSC for controlling a midi app (SetBFree, an Hammond organ emulator) and I'm trying to use a multifader, but this seems to be buggy. 

- I configured a simple fader for testing, and it works well:
    - Range: {"min": 0, "max": 127}
    - precision: 0
    - adress: /control
    - preargs: [0,1]
    - target : ["midi:openstage"]
- Then I configured a multifader in the same maneer, taking care to set `split` to false.

When moving multifader's faders, I get this error in console logs:
```
ERROR: MIDI: could not convert osc args to midi message (/control 0 1 4 4)
```

I investigate a little and found out a "workaround" to the problem; I'll submit PR just after this issue. I don't think it is a "long term" fix, but it works, and I can play with my multifader waiting for the bug to be fixed in master. (I suppose this should go to multifader.js, not sure about the "clean" way to do).

Thanks again for this wonderful app by the way :)

**Comment by jean-emmanuel** [comment]
Hi, thank you for the feedback. The problem here is that you are not sending the correct number of arguments to produce a valid MIDI message. As stated [here](http://osc.ammd.net/extras/midi/#control-channel-cc-value), `/control` expects 3 arguments (channel, cc and value). The multifader sends two values by default (slider's index, value), all you need in preArgs is one value to determine the channel.

**Comment by brunetton** [comment]
Ok, got it ! Thanks.
