### ISSUE TITLE
RGB Widget

### ISSUE THREAD

**Issue by ManuelWaldmann** [jean-emmanuel/open-stage-control#252]
Hello, is it possible to send 3 ranges with the rgb widget? Similar to the xy widget with only 3 instead of 2 ranges.
I would like to control a rgb light. whose osc command for white is /rgb <100> <100> <100>.
So for each color (red, green, blue) a range of 0-100.
or is the widget not intended for that?

Best regards

**Comment by jean-emmanuel** [comment]
Currently the rgb's range is fixed to 0-255, I could add an option for that. I the meantime, you can filter the rgb's output with an input widget: set the input's `value` property to `#{@{rgb_id} / 2.55}` (replace `rgb_id` with the actual id of the widget) and don't forget to set the osc related properties as well.  Here are the docs for the syntax I'm using : http://osc.ammd.net/extras/advanced-property-syntax/

**Comment by jean-emmanuel** [comment]
-> v0.28.0

**Comment by jgastonraoul** [comment]
Is there a way to have a float output on this widget ?
I need to send 3 messages (on independent message for each component) between 1. and 1.1.

**Comment by jean-emmanuel** [comment]
Hi ! There was a bug rounding the rgb values, it is now fixed in v0.41.3.
You can split the pad's messages using the `split` property (see https://osc.ammd.net/widgets-reference/#rgb_split)
Please do open a new issue if you are having trouble, posts in old closed issues are likely to be forgotten and notify the original issue's author unnecessarily.

**Comment by jgastonraoul** [comment]
What a quick fix, thank you !
