### ISSUE TITLE
TouchOSC2MIDI (TouchOSC) and Open Stage Control - possible?

### ISSUE THREAD

**Issue by vedranius** [jean-emmanuel/open-stage-control#318]
Hi,
I'd like to use Open Stage Control to control Raspberry Pi /w PiSound running TouchOSC2MIDI, but I'm not sure if that's possible, and if it I'd like to know how to set it up.

https://github.com/velolala/touchosc2midi

Many thanks and I hope someone could help me with that :) 

BR

**Comment by jean-emmanuel** [comment]
Hi, have you tried Open Stage Control's MIDI feaures ? https://osc.ammd.net/extras/midi/

**Comment by vedranius** [comment]
Hi @jean-emmanuel I'm kinda confused how this should work.

Should I run a Open Stage Control server on RPi 3 (which I want to control) or on a PC (Windows) for example?
And then to run for example osc2midi on RPi 3?

I'm using Windows to run Open Stage Control server but I'm not sure how to configure it.
In OSC2MIDI on RPi 3 in it's monitor view I'm getting commands, but further in MODEP software (used by PiSound - Blokas.io) I don't get anything.

So not sure what the problem might be, on which side.
1. OSC2MIDI not communicating with MODEP because I don't know how to set in and out to 0
2. MODEP not recognizing commands sent by Open Stage Control
3. or something else... 

Thank you!

**Comment by jean-emmanuel** [comment]
There are two different solutions:

- running open-stage-control server on the rpi and make it send MIDI as explained in the docs, you will be able to access the interface with chrome/chromium from any other computer on the network
- assuming touchosc2midi and MODEP are connected (I have never used those two): configuring your open-stage-control interface to send exactly what touchosc2midi expects (something like `/midi byte1 byte2 byte3 byte4`, you should write the bytes in decimal instead of hexadecimal though).

In both case, you'll have to carefully configure your widgets to make sure they send the right messages using their `address` and `preArgs` properties.
