### ISSUE TITLE
XY Pad Midi Conversion

### ISSUE THREAD

**Issue by CamoKrooked** [jean-emmanuel/open-stage-control#324]
Hey,

I am currently trying to figure out if this is even possible as of now:
I want the XY Pad to send CCs for X,Y and Touch. The XY parameters are set to split. 
But the problem is that this causes the address to add /x and /y behind /control, so that is probably why it spits out this message in the console:
ERROR: MIDI: could not convert osc args to midi message (/control/x 1)
ERROR: MIDI: could not convert osc args to midi message (/control/y 80)

Is there any workaround for this? Midi Settings are fully functional - Sliders etc are sending midi normally.

Thanks!

Edit:
custom object names "control" in the split section doesn't help either. Also, would it be possible to set preArgs for touchAddress, x and y differently?

**Comment by jean-emmanuel** [comment]
> Also, would it be possible to set preArgs for touchAddress, x and y differently?

Nope, if you want to control three different MIDI controls with a single xy, you have two solutions:

1. configure the xy so that only the /touch message works, retreive the x and y values in two input widgets (with their `value` properties to `#{@{xy_id}[0]}` and `#{@{xy_id}[1]}` respectively, and configure these widgets to send the desired MIDI messages.

2. Filter the app's osc messages a do the routing fom a [custom module](https://osc.ammd.net/extras/custom-module/), something like :

```js
(function(){

    return {
        
        oscOutFilter:function(data){
            // Filter outgoing osc messages

            var {address, args, host, port} = data

            if (address === '/control/x') {
                // alter args here
            }

            if (address === '/control/y') {
                // alter args here
            }

            if (address === '/control/touch') {
                // alter args here
            }

            return {address, args, host, port}
        }
        
    }

})()
```

**Comment by CamoKrooked** [comment]
Wow, perfect! Haven't thought of that :)
Thanks a lot!
