### ISSUE TITLE
When do formulas send their value?

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#342]
Hello

I am using a switch as a way to store and display the state of some buttons.

I would like to send the values of these buttons (or better, a complete dictionary) when a state changes.

I have used a formula, I see the formula is changing, but nothing is sent via OSC (I have set ``1==1`` as condition)

An example is attached...

[switch_formula.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/2225802/switch_formula.json.txt)

I would expect some OSC to be sent each time a button is pressed, but it seems I misunderstood something...

Thx

**Comment by jean-emmanuel** [comment]
As stated in the docs: 
> Since v0.24.0, any widget property can be defined using math expressions. Formula widget is deprecated and will be removed in a future release.

You should use an input instead and put the math logic in its `value` property: 
```
#{
values(@{switch_1.values})
}
```
Now the thing is a property update only triggers osc sendings when it's initiated by a `value` change, but currently any non-dynamic property update in the event chain cancels this behavior. Since the switch's `values` property is not dynamic, you need to bind the input's `value` to the toggles' values directly to ensure osc is sent : 
```
#{
#semi-colons -> values not shown but bound
@{toggle_1};@{toggle_2};
values(@{switch_1.values})
}
```

I'll try to prevent non-dynamic props updates from breaking this logic, to be continued...

**Comment by jean-emmanuel** [comment]
As of 556892f9, non-dynamic props updates should not break osc sending event chains, so this should be enough:
```
#{
values(@{switch_1.values})
}
```

**Comment by cyberic99** [comment]
Thx!

Even better, I can get the whole JSON dict if I simply put 
```
#{
@{switch_1.values}
}
```
I get fior instance:
```
{"toggle1":1,"toggle2":0}
```
That's perfect!

**Comment by jean-emmanuel** [comment]
-> v0.34.0
