### ISSUE TITLE
Initial values

### ISSUE THREAD

**Issue by groolot** [jean-emmanuel/open-stage-control#36]
Each control do not have any initial value. This is an issue while settings some UI to anything different from everything ZERO

**Comment by groolot** [comment]
We should save the current state while saving the file.

**Comment by jean-emmanuel** [comment]
> Each control do not have any initial value. This is an issue while settings some UI to anything different from everything ZERO

This was actually by design : since the initial state of the interface is not sent through OSC, it does not represent anything relevant; that being said I, if it doesn't represent anything, then I don't see why it couldn't be customized.

> We should save the current state while saving the file.
I disagree : widget's properties and states are separated. If a widget's value is to be stored in the session file, it'd be its initial value, as suggested above, but I think it'd wrong to assume a widget's state should become its initial value when saving the session. The app's state can already be stored and exported in a separate file

**Comment by jean-emmanuel** [comment]
[v0.11.0] introduces a `value` option for widgets (documented @ http://osc.ammd.net/user-guide/widgets-generics/#value)

**Comment by groolot** [comment]
youpi!
