### ISSUE TITLE
clone can't resolve osc addresses with @{parent.address}

### ISSUE THREAD

**Issue by MartinHN** [jean-emmanuel/open-stage-control#379]
hi guys,
great work out there!
just struggling with dynamic osc addresses in clones.

it seems that if widget1 has an osc address depending on @{parent.address}
clone of widget1 cannot resolve the @{parent.addresss} part and replace it with undefined

I've tried to look down in the code, it may be the widget.cachedProps  thats not up to date, but don't understand much more for now.

a simple file showing the bug 
[bug_clone.json.zip](https://github.com/jean-emmanuel/open-stage-control/files/2459575/bug_clone.json.zip)

**Comment by jean-emmanuel** [comment]
Hi, thanks for your feedback. The problem here is that the cloned widget is actually wrapped in a widget, this messes with the inheritance logic in some cases (`@{parent.address}` attempts to return `clone_1`'s `address` which is not part of its class definition. Making this clone wrapper more transparent (ie ignored in the @{parent} call stack) might be a solution. I'll keep you posted.

**Comment by jean-emmanuel** [comment]
Yep, it fixes it :)

**Comment by MartinHN** [comment]
indeed, many thanks!
