### ISSUE TITLE
Dropdown widget hangs

### ISSUE THREAD

**Issue by PLu55** [jean-emmanuel/open-stage-control#446]
The Dropdown widget occasionally hangs the application. When clicking on it it opens a completely white area and the application gets frozen.

Open Stage Control 0.40.3
Linux PLulix 4.18.0-13-lowlatency #14-Ubuntu SMP PREEMPT Wed Dec 5 12:12:14 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Kubuntu 18.10

**Comment by jean-emmanuel** [comment]
Hi, thanks for reporting your issue. Here are a few questions that could help me tracking it:

- are you using prebuilt binaries from the release page ?
- are you accessing the app with the built-in client browser  or with a third party browser ?
- does the issue occur when accessing the app with chromium instead of the built-in client browser ? (please provide chromium version)
- does the issue occur with a new session containing just a dropdown widget ? (if not please upload your session file here and provide the app's startup settings if any)

**Comment by PLu55** [comment]
* Yes, I'm using the prebuilt binaries, the open-stage-control-0.40.3-amd64.deb installer.
* I'm using the build-in client.
* its not easy to provoke the problem, I'll run my system with the Chromium browse for a while and see if it happen there, I'll be back to you on that.
* it occures with an new empty session with just a one single dropdown added.

**Comment by PLu55** [comment]
Wupp, wrong presse wrong button, sorry.

**Comment by jean-emmanuel** [comment]
Ok thanks for the details ! Keep me posted if you manage to get a reproducible pattern.

**Comment by PLu55** [comment]
The only pattern is that there is no pattern. It can freeze immediately on the first click in  a completely fresh session with only a dropdown added or it can run for a long time with the dropdown activated many times without any problems.

**Comment by PLu55** [comment]
I have now been running for a while with the built in browser with the #:disable-gpu #t flag and there has not been any crash so far. 

Another observation is that it seams like the crashes appear immediately after the content has been changed or direct after the creation of the dropdown.

**Comment by jean-emmanuel** [comment]
Thanks !
Since this is a issue related to this specific chromium version and system, I think the `--disable-gpu` trick is good enough.
