### ISSUE TITLE
issue when receiving a fader value while dragging it

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#449]
Hello

I experienced a weird bug:

I have a fader with snap=false, spring=false

I click on the fader, then drag it

Before releasing the mouse button, this fader receives a value (which is more or less the current fader value), when it crosses the '0' value

When I release the fader, it goes back to the value that was received.

I would have expected it to stay at the same position

Please see the raw screencast demoing the bug

![screencast](https://user-images.githubusercontent.com/193917/50551752-5869f200-0c86-11e9-87b9-c10e79de29a7.gif)

**Comment by jean-emmanuel** [comment]
Actually it's by design, values that are received while dragging are queued and applied after releasing, this is to ensure the fader is correctly synced with feedback messages. This makes sense when the feedback is either consistent or inexistent, here you only send feedback for `0`, hence the unexpected behavior. I'm not sure yet if it should be optional.

**Comment by jean-emmanuel** [comment]
603e92938caa3cc8e379d2652b5199e88901c35e:
> sliders/pads: when receiving feedback while touched, the widget waits to be released before updating to the latest received value.

This choice was made a year ago, I'm not entirely convinced of its relevance though, maybe some feedback from other users could help deciding whether it should be kept or not. CC @ovenwerks @MartinHN @kdejaeger @Sebastian-blu @danielappelt

**Comment by kdejaeger** [comment]
No opinion about this ...

**Comment by cyberic99** [comment]
Thanks for your feedback @ovenwerks.

In fact, the software at the other end is custom so we have total control over it.

So you say that OSC feedback should be sent back continuously by the "DAW", right? and not only around 0?

I initially did that to spare round trips between o-s-c and our software...

But this totally makes sense...

However, I have to check how many messages o-s-c sends while you keep dragging the fader...

Is there a threshold on that, @jean-emmanuel ?

**Comment by jean-emmanuel** [comment]
Thanks @ovenwerks !

Well @cyberic99 o-s-c has no fixed sending rate, it depends on how fast you move the slider... Why are you sending feedback for `0` in the first place ?

**Comment by cyberic99** [comment]
In fact our use case i a bit more complicate, but maybe I am doing it the wrong way.

In addition to the fader, we have a 'reverse' toggle button

So when the speed sign changes (ie it crosses 0), the reverse button state changes, so o-s-c sends a /REVERSE event

The reverse button can also be toggled manually.

When the reverse state changes, its new state is sent to our software, which takes the opposite of the current speed and send it back to o-s-c.

This is why I receive a /SPEED when crossing 0, because my reverse button has been toggled.

There is certainly a better way to implement it, but the way I'm doing it now is triggering this behavior (that can be seen as a bug or a feature ;-))

**Comment by jean-emmanuel** [comment]
This feedback seems to be relevant only when interacting with the reverse toggle button, but not when the slider crosses zero (since `0` and `-0` are the same, you could safely prevent this feedback message from being sent).

Anyway, it could make sense to allow disabling this behavior on o-s-c's end, just gotta find the appropriate name for it.

**Comment by cyberic99** [comment]
> This feedback seems to be relevant only when interacting with the reverse toggle button, but not when the slider crosses zero (since `0` and `-0` are the same, you could safely prevent this feedback message from being sent).

How could I do that?

Can I prevent the button from sending its value when it changes, but still sending it when pressed?

I don't know if you really have to do something regarding o-s-c... I thought it was a bug, that's why I reported it...

**Comment by cyberic99** [comment]
> You could add a condition in your custom software to prevent feedback when the slider is beeing touched (use the fader's `touchAddress` to tell the software when it's beeing dragged).

Right.
It is doable but this means the software must keep the state of each fader and such...

I can also enable OSC feedback for both speed and reverse buttons...

Not sure about the impact on performance...

Is there a way to ignore incoming OSC values while dragging? Like dynamically changing the target?

**Comment by jean-emmanuel** [comment]
> It is doable but this means the software must keep the state of each fader and such...
Sound very reasonable to me... ;) Besides, you can do it from o-s-c custom module if you need.

**Comment by MartinHN** [comment]
Hi,
If i understand well your problem i think that you should let your app
handle the reverse logic: when the slider change sign , the app toggles
reverse but doesnt send back fader value to the client its receiving from.
If the app receive a reverse command it sends only the fader changed value.

Its a general workflow i try to have with o-s-c kinds of tools : for me
these are best fitted to visualize but not to handle core application
logic, i inevitably come across these kind of chicken and egg problems if
both client and server share (and possibly duplicate) logic. So if you have
control over the app better to fit this logic in it i think.

**Comment by cyberic99** [comment]
> > It is doable but this means the software must keep the state of each fader and such...
> 
> Sound very reasonable to me... ;) Besides, you can do it from o-s-c custom module if you need.

Yes but it makes my fader handling code stateful...

**Comment by cyberic99** [comment]
> when the slider change sign , the app toggles reverse but doesnt send back fader value to the client its receiving from. If the app receive a reverse command it sends only the fader changed value.

Thx for your feedback @MartinHN 

In this case, how can I manually trigger a reverse?

**Comment by cyberic99** [comment]
> Toggle > send "reverse" command to the app > send fader feedback to o-s-c
> Fader > send "speed" command to the app > send toggle feedback to o-s-c

You're right, this should work

I'll try this and let you know.

Currently the toggle value is set dynamically to 0 or 1 in o-s-c depending on the sign of the speed fader...

That is what makes the workflow fail, I think...

**Comment by cyberic99** [comment]
>  It is doable but this means the software must keep the state of each fader and such...
> Of course. Any time you have a remote control the local SW must also keep track of the state of all controls. The sw should be able to run without the remote control as well as with, so you are keeping track of all these values in any case.

Yes of course

But with this solutionI have also to keep the 'touch' state

And is itthe order of the OSC messages processing really guaranteed?

In our software we have a single thread doing the processing sequentially

But some OSC implementations start a thread each time they receive a message, so the order of 'touch' ang 'drag' event could be messed up ...

(again, this is not the case with my software)


> it sounds like you are using the same OSC path for both the fader and the reverse button. That does not sound right.

No no, I use ``/<STRIP NUMBER>/REVERSE`` and ``/<STRIP NUMBER>/SPEED``

> Also, when the direction switch sends it's message, the SW would only check if the current direction is correct. If it is, it should not change the speed.

Right but if I click on the toggle, how can I know which direction is correct?

I still know the last speed message I received, but if the user clicks on the toggle, he *wants*  to invert the speed

> Not sure about the impact on performance...
> OSC control at least for things like faders is generally not real time. As such it should not be dealt with in a real time thread. That is most OSC libs are not real time (might wait a while for something else to happen).

Humm I didn't know that... OK.

I'll try to get the smaller latency as possible anyway... ATM it seems possible to get smth well under 10ms with a tablet and a computer

> > Is there a way to ignore incoming OSC values while dragging? Like dynamically changing the target?
> That would be up to your own SW. To do something like that... save the value each time it comes in... apply the last value when touch off is received. 

Yes, but if there is any feedback while dragging, this is this value that is applied....

this is why I opened this issue

> This is good because if you are moving a fader slow, you probably want more (finer) values and if you are moving it fast you just want to go from point A to point B. The sw that is being controled is reponsible for any needed smoothing (low pass filtering) of the control.

I get that.

But I think messages are filtered in a way or another at the sending side too

> I have not had problems with too many OSC messages untill I am sending several hundred messages as when a control surface is banked and every control for every channel must be changed at once, but this is sending not receiving. I have found receiving takes care of itself.

Ok

Thx for your opinions and this discussion!

**Comment by ovenwerks** [comment]
On Wed, 2 Jan 2019, cyberic99 wrote:

>
>       It is doable but this means the software must keep the state of each
>       fader and such...
>       Of course. Any time you have a remote control the local SW must also
>       keep track of the state of all controls. The sw should be able to run
>       without the remote control as well as with, so you are keeping track
>       of all these values in any case.
> 
> Yes of course
> 
> But with this solutionI have also to keep the 'touch' state

One int does not seem like a lot of trouble...

> And is itthe order of the OSC messages processing really guaranteed?

No, never. OSC is UDP and therefore delivery order across the network is 
not guaranteed. There is not even any reasurance any one packet will 
arrive even when dealing with localhost as I have found out. It is 
possible to overwhelm the transmit que. The network stack is also allowed 
to reorder the packets it sends for it's own reasons. It is possible to 
use TCP but that may be slower as there is more overhead and of course if 
there is a missing packet, subsquent packets are not released till the 
missing one is refetched.

> In our software we have a single thread doing the processing sequentially

What OS are you using that you can say this with such assurance? DOS? OSC 
already uses the OS network stack which runs in a kernel thread after all.

> But some OSC implementations start a thread each time they receive a message, so
> the order of 'touch' ang 'drag' event could be messed up ...

Well actually some OS thread makes a call to one of the SW calls, but is 
probably all the same (network) thread.

That is something you should protect yourself from with good programming 
anyway. If you receive a fader value, you know there is a touch already 
even if it hasn't arrived yet, so set it. The real problem is when does 
the touch release happen? Or what if the touch release comes before the 
last fader value? In my case, I can't control what controller is being 
used, so a touch command may not ever show up. So I create a "fake" touch 
that times out if a new fade value doesn't show up within a certain amount 
of time. Now in my case touch is more important because it is used for 
automation and when touch is off, the DAW may send automated fader values, 
but as soon as the user touches the fader it should not try to move their 
finger (assuming a motor fader).

In your case, I would not use touch anyway. I would use the fader values 
as they come in. I personally would not add a reverse switch if the fader 
has both positive and negative values as the fader already has that 
functionality. I might have "play" and "reverse" buttons that set the 
speed to 1 and -1 and stop would set things to 0. (in fact I do) but the 
feedback for all three of these is linked. if I hit play, I have /play i 1
I have /stop i 0, I have /rew i 0 and I have /ff i 0. Every time I change 
any one of those buttons I have to set all of them. In my case I do not 
use a fader but rather an encoder which might control speed or possition 
so it can be used for speed, scrub or jog. (scrub is sort of jog with 
audio as in the days of tape when the reel could be turned to find the 
exact place a sound starts or stops) Anyway. with both speed buttons and a 
speed fader, the controled device should expect the user to use only one 
control at a time. If the fader is being used then the buttons are not and 
vise versa.

Anyway, I think I have hit some rabbit trail. looking farther up, the main 
problem seems to be that your reverse button set speed to 0. If the 
reverse button is pressed:
if ((speed < 0 && reverse = 0) || (speed > 0 && reverse = 1)) {
 	// wrong direction
 	speed = speed * -1;
}
send /fader f speed

Fader is moved:
if (fader < 0) {
 	reverse = 1;
} else {
 	reverse = 0;
}
speed = fader;
send /reverse i reverse

Done.

If you have a start button it also has to handle all these 
variables. You could choose to leave reverse as is if the fader goes to 0 
as would be reasonable if you also had a start switch. For a start switch:
if (reverse) {
 	speed = -1;
} else {
 	speed = 1;
}
send /fader f speed

I know that my use of DAW as the controlled SW may not match what you are 
doing. Your application may not involve audio at all and that is ok. Just 
take any instance of DAW and understand it means what is being controlled 
as compared to the controller.

>       Also, when the direction switch sends it's message, the SW would only
>       check if the current direction is correct. If it is, it should not
>       change the speed.
> 
> Right but if I click on the toggle, how can I know which direction is correct?

The toggles in O-S-C send 1 when the "light" goes on and 0 when the 
"light" goes off. That is what I used above. The reverse toggle should not 
have any reference to the speed fader in O-S-C and the fader should not 
have any reference to the reverse toggle. They are tottally sepparate on 
the controller.

> I'll try to get the smaller latency as possible anyway... ATM it seems possible
> to get smth well under 10ms with a tablet and a computer

wireless network is never real time. I have found they can work well most 
of the time except when needed. Any interference from other wireless 
systems, even on a different network, causes colisions and resends.

> Yes, but if there is any feedback while dragging, this is this value that is
> applied....

Don't send feedback while touch:
call_to_deal_with_fader (fader_value)
{
 	temp_fader = fader_value;
}

call_to_deal_with_touch (touch_value) {
 	touch = touch_value;
 	if (!touch) {
 		set_speed (temp_fader);
 	}
}

set_speed (in_speed)
{
 	speed = in_speed;
 	send /fader f speed;
 	if (speed < 0) {
 		send /reverse i 1;
 	} else {
 		send /reverse i 0;
 	}
}

> But I think messages are filtered in a way or another at the sending side too

By time, the mouse position is only looked at when the GUI 
cycles through, which it does not do continuously. The gui sets a timer 
and then goes idle, when the timer finishes the OS sends an irq to the GUI 
and the gui checks where the mouse is and if the mouse buttons have 
changed and if a key has been typed. All mouse positions in between are 
lost. Otherwise the application (or the GUI) would be using 100% CPU going 
in circles. (of course the OS only allows each pocess so much time before 
switching to the next as well) I have over simplified :)

**Comment by cyberic99** [comment]
> > In our software we have a single thread doing the processing sequentially
> What OS are you using that you can say this with such assurance? DOS? OSC already uses the OS network stack which runs in a kernel thread after all.

I cannot be sure about the order

but at least I am sure that OSC messages get processed one after the other, and not simultaneously by multiple threads

> looking farther up, the main problem seems to be that your reverse button set speed to 0.

do you say that because of the video I attached?
Yes that it what happens. It sets the speed close to 0 and also sends feedback, but only at this moment

I will rework that, but I opened this issue because I found o-s-c behavior surprising at first.

>  If the reverse button is pressed: if ((speed < 0 && reverse = 0) || (speed > 0 && reverse = 1)) { // wrong direction speed = speed * -1; } send /fader f speed Fader is moved: if (fader < 0) { reverse = 1; } else { reverse = 0; } speed = fader; send /reverse i reverse Done.

Yeah right, I'll try to do that and will study @jean-emmanuel suggestion too.

>  The reverse toggle should not have any reference to the speed fader in O-S-C and the fader should not have any reference to the reverse toggle. They are tottally sepparate on the controller.

that makes sense

> I'll try to get the smaller latency as possible anyway... ATM it seems possible to get smth well under 10ms with a tablet and a computer
> wireless network is never real time. I have found they can work well most of the time except when needed. Any interference from other wireless systems, even on a different network, causes colisions and resends.

Sure. The tablet is connected to the computer via USB

> > But I think messages are filtered in a way or another at the sending side too
> By time, the mouse position is only looked at when the GUI cycles through, which it does not do continuously. The gui sets a timer and then goes idle, when the timer finishes the OS sends an irq to the GUI and the gui checks where the mouse is and if the mouse buttons have changed and if a key has been typed. 

Yes I know. I was wandering if this timer was tweakable or not

**Comment by cyberic99** [comment]
OK, I have implemented a mix between what @ovenwerks and @jean-emmanuel suggested.
It seems to work correctly.

The calculations, triggers etc... are done on the server and not in o-s-c

Anyway I learned a lot in this issue, thanks everyone!

**Comment by jean-emmanuel** [comment]
Thanks everyone for your input, sorry @ those I've pinged for the many notifications !
