### ISSUE TITLE
Midi Support

### ISSUE THREAD

**Issue by lupin3rd** [jean-emmanuel/open-stage-control#45]
Hi, thanks for this wonderful free software :-)
I use it to control via OSC some VJ puredata patches...
Very often people use Midi controller to control UI. Do you think about add midi support to open stage control?
Thank you

**Comment by jean-emmanuel** [comment]
Thanks for the kind word :)

I might implement it someday thanks to [node-midi](https://github.com/justinlatimer/node-midi), I'll let you know !

**Comment by jean-emmanuel** [comment]
Midi support is on its way, it'll consist in: 

- declaring midi devices when starting the app (one device = 1 input / 1 output)
- making widgets send specific messages that will be interpreted as midi messages and sent to midi targets ( `midi:device_name` instead of `ip:port`)

Work-in-progress documentation: https://github.com/jean-emmanuel/open-stage-control/blob/master/resources/docs/user-guide/midi.md

**Comment by jean-emmanuel** [comment]
https://github.com/jean-emmanuel/open-stage-control/releases/tag/v0.17.0

**Comment by lupin3rd** [comment]
thank you very much!!!

**Comment by jean-emmanuel** [comment]
You are welcome ! MIDI support was actually broken in v0.17.0, please use [v0.17.1](https://github.com/jean-emmanuel/open-stage-control/releases/tag/v0.17.1)
