### ISSUE TITLE
custom backend

### ISSUE THREAD

**Issue by amir-arad** [jean-emmanuel/open-stage-control#52]
I really like this project!

I'd like to use it to build custom dashboards to a cool game that I play with my friends
https://github.com/daid/EmptyEpsilon

for that I need a library that serves as a programmatic API to the session's state and the remote control API. do you have any suggestions as to where would be a good place to start hacking?

**Comment by amir-arad** [comment]
to clarify, what I'm missing is some javascript module that supplies API such as `oscClient.getValue(location)` `oscClient.setValue(location, args)`

**Comment by jean-emmanuel** [comment]
Hi, thanks for your interest in the project !

For now, the server instance doesn't hold the session's state, all it does is sending back every sent message to all clients and let them update matching widgets if any (osc address + target + number of arguments), so that every client represents the latest values they could have been sending. Nothing has been been done so far to disambiguate different clients that use identical widgets. Open stage control doesn't offer much in term of javascript API, it's not that well coded, haha :). 

If you need non-ambiguous clients, running multiple server instances and interracting with them through OSC seems the easiest way to go: you'd write some middleware that filters all outputed messages, store corresponding states changes against instances Id

**Comment by jean-emmanuel** [comment]
Note: please read previous message on github, it was sent unfinished by mistake.

**Comment by amir-arad** [comment]
I think I can work with an ambiguous client library that is initialized using the same session definition as the server. The "real" state for my use case is in another server, so I can periodically push-update osc, and propagate changes made by other clients to the server holding the state.
