### ISSUE TITLE
[Bug] Suddenly values from plots are sent via osc

### ISSUE THREAD

**Issue by docb** [jean-emmanuel/open-stage-control#592]
2d1ddd335396de8a07193afb2fb18dbee946fdc3 normal options.
When clicking Sendall values from Plots are sent (seems to be a new behaviour as these unexpected messages were suddenly reported by my osc receiver). I assume this is not intended as i have no option to bypass osc as i could do with control widgets.
The only workaround is to remove the path in the plot/text etc which is changed then to "auto" because then there comes an error message in the stdout/err of o-s-c
auto [ { type: 's', value: '[0,0]' },
  { type: 's', value: '[0.02,1]' },
  { type: 's', value: '[1.6400000000000001,1]' },
  { type: 's', value: '[2.37,1]' },
  { type: 's', value: '[2.39,0]' } ] localhost 10000
OSC error: malformed address: "auto" 
and the message is not sent out.
However i assume this may also not be intended.

**Comment by jean-emmanuel** [comment]
Thanks for the report. The bug was actually affecting all the other `plot/*` widgets and started affecting this particular one after commit https://github.com/jean-emmanuel/open-stage-control/commit/2cc705a1e0cea202eafe9295f0ca0db26d073d41. As of next version, these widgets will all behave as if `bypass` was always `true`.

> [...] which is changed then to "auto" 

That's been around for a while too but I didn't took the time to get rid of it. It's now fixed in git.

**Comment by jean-emmanuel** [comment]
Fixed in v0.49.2
