### ISSUE TITLE
[Bug] /STATE/GET and image containing base64 encoded file : (ERROR, UDP) send EMSGSIZE

### ISSUE THREAD

**Issue by matcham** [jean-emmanuel/open-stage-control#664]
When a session contains an image with it's value prop = "data:image/svg+xml;base64,PD94bWwgdmV...."
sending /STATE/GET to the server returns an error : 

(DEBUG, OSC) In:  { address: '/STATE/GET', args: '127.0.0.1:8003' } From: 127.0.0.1:59514
(DEBUG, OSC) Out:  {
  address: '/STATE/GET',
  args: [
    {
      type: 's',
      value: '{"image_1":"data:image/svg+xml;base64,PD94bWwgdmVyc2lvb.....
    }
  ]
} To: 127.0.0.1:8003
(ERROR, UDP) send EMSGSIZE 127.0.0.1:8003

obviously a base64 image can be very big.. too big for an osc message (?)

could it be filterered when it receives /STATE/GET ?
(do not return image value if it's content is base64)
..or ?

anyway, actually it breaks the /STATE/GET function.

**Comment by jean-emmanuel** [comment]
I'm not sure hiding the issue is a good solution : filtering out base64 images would mean silently failing at sending the state message. UDP packets have a size limit that O-S-C can't change. I think the solution here is to not store big images in the session (image files stored in the same folder as the session file can be accessed just with the file name since image paths are first resolved against the session's location).

However if needed, filtering outgoing osc messages is possible with a custom module.
