### ISSUE TITLE
[Bug] Matrix children props not updating correctly when referencing other widget

### ISSUE THREAD

**Issue by akaztp** [jean-emmanuel/open-stage-control#701]
- Open Stage Control version: 1.8.15
- Operating system: Windows 10
- Open Stage Control options: ?
- Client type: built in
- Session file: bug-session.txt
- Custom module: no

How to reproduce:
- Create "matrix_view" with buttons and props: {"label": "#{(@{matrix_source})[$]}"}
- Create "matrix_source" with buttons.
- Pushing first "matrix_source" button will always display its correct state on the first button of "matrix_view"
- Pushing non-first "matrix_source" buttons will not display its correct state on the corresponding button of "matrix_view". After pushing non-first button, if first button is pushed, all labels in "matrix_view" are updated correctly.

[bug-session.txt](https://github.com/jean-emmanuel/open-stage-control/files/6252337/bug-session.txt)

Thank you!

**Comment by jean-emmanuel** [comment]
Could you please provide more information and step by step instructions to reproduce the issue ?

**Comment by akaztp** [comment]
I've updated the first post. It was a too soon "ENTER" typo...

**Comment by jean-emmanuel** [comment]
You've hit a limitation with the advanced syntaxes + matrices :  to determine whether the `props` property has changed, OSC evaluates its content with `$` equals to `0` and compares it to the last cached result, hence the issue not occurring when pushing the first button (whose index is `0`).

To circumvent the issue you can either:
- force the `props` property to always change whenever it's evaluated* by injecting a randomly generated number in it:
```js
{
  "label": "#{(@{matrix_source})[$]}",
  "_rand": #{Math.random()}
}
``` 
* what triggers the evaluation is the value updates from "matrix_source" because of the presence of "@{matrix_source}"

- use the clone matrix pattern  as seen in "clone_and_variables.json" from [these examples](https://openstagecontrol.discourse.group/t/feature-demo-property-inheritance-scripting-clones/851).

**Comment by akaztp** [comment]
Thanks for your fast the thorough response.
I've managed to solve it by adding the props `"_forceUpdate": @{matrix-source}` instead of the random!

**Comment by jean-emmanuel** [comment]
Works too ! :)
