### ISSUE TITLE
[Feature] Support rtpmidi

### ISSUE THREAD

**Issue by jpnielsen** [jean-emmanuel/open-stage-control#746]
Support rtpmidi 

https://github.com/jdachtera/node-rtpmidi

I would use it to connect O-S-C on Linux through [rtpmidi ](https://www.tobias-erichsen.de/software/rtpmidi.html) to Ableton on Windows

**Comment by jpnielsen** [comment]
I tried installing rtpmidid on linux yesterday, but got a coredump when trying to start it.

https://github.com/davidmoreno/rtpmidid/issues/74

If you know of other "libre" ways to do midi over network between windows and linux, I'd like to know.

Thank you - I really appreciate your software.

**Comment by jean-emmanuel** [comment]
rtpmidi will not be added in open stage control, its MIDI layer is kept as thin as possible because the software's main focus is OSC. Using https://github.com/davidmoreno/rtpmidid alongside o-s-c seems to be the best option.

If your use case is as simple as using the linux system as a remote to control the other, running the o-s-c server on the latter would work too.

**Comment by jpnielsen** [comment]
No problem, thanks.
