### ISSUE TITLE
[Bug] Setting HTML value in HTML frame widget fails

### ISSUE THREAD

**Issue by DjTuxeedo** [jean-emmanuel/open-stage-control#813]
Hey there,
first of all: "Open Stage Control is awesome!" I love working with it.
I'm using version 1.22.0 and I'm sending OSC messages via a supercollider script.
I figured out how I can manipulate some widgets via OSC messsages. 
Let's say this works to manipulate a fader from supercollider -> OpenStageControl:
n.sendMsg("/fader_1", 0.5);
Or change a text in a text display widget:
n.sendMsg("/text_1", "HelloWorld");

But I cannot figure out how to change the html body of an HTML frame widget. I've tried:

n.sendMsg("/html_1","HelloWorld");
n.sendMsg("/html_1/html","HelloWorld");
n.sendMsg("/html_1/value","HelloWorld");
n.sendMsg("/html_1/html","HelloWorld");
n.sendMsg("/html_1","{\"html\":\"HelloWorld\"}");

None of these change anything in the frontend. But i do get debug messages that these messages have been received.

Could somebody give me a pointer how to manipulate the html body of an html widget?
Thank you so much

**Comment by DjTuxeedo** [comment]
btw. same thing with the SVG frame widget

**Comment by jean-emmanuel** [comment]
Thanks !

The html/svg widgets don't hold an actual value, it's the content of their `html` or `svg` properties you need to feed to change their html/svg content. To expose these properties to osc messages the simplest way is to write for example
```
OSC{example}
```
in the the property, then the content of that piece of code will depend on what you send to open stage control on osc address `/widget_address/example` 
This syntax is documented [here](https://openstagecontrol.ammd.net/docs/widgets/advanced-syntaxes/#osc-listeners-oscaddress-default-usepreargs).

For further usage question please use the forums so that more users can help or benefit from the answers : https://openstagecontrol.discourse.group/
